- labman/gui/handlers/base.py
- labman/gui/templates/error.html
We probably want to make this page prettier in the future but for now this is really useful for debugging when an unexpected error occurs during development.
> Adding error page

- labman/db/composition.py
- labman/db/container.py
- labman/db/support_files/labman.dbs
- labman/db/support_files/labman.html
- labman/db/tests/test_composition.py
I'm still unsure on how the primer_set_composition and primer_composition objects should look like, so I just put the class name so I can create the other classes. There is a couple of TODO's that will be easier to implement once we have the base classes and we can start interacting with all the objects.
I will do another PR later with the "Processes" objects
> Composition objects

- labman/db/base.py
- labman/db/equipment.py
- labman/db/process.py
- labman/db/tests/test_equipment.py
- labman/db/tests/test_process.py
With this PR all the objects that are represented in the DB are currently created.
From here forward we need to start creating the functions/methods required to perform the wet lab tasks.
> Process and Equipment objs

- labman/db/composition.py
- labman/db/equipment.py
- labman/db/plate.py
- labman/db/process.py
- labman/db/testing.py
- labman/db/tests/test_composition.py
- labman/db/tests/test_equipment.py
- labman/db/tests/test_plate.py
- labman/db/tests/test_process.py
- labman/gui/handlers/composition_handlers/__init__.py
- labman/gui/handlers/composition_handlers/reagent_composition.py
- labman/gui/handlers/composition_handlers/test/__init__.py
- labman/gui/handlers/composition_handlers/test/test_reagent_composition.py
- labman/gui/handlers/plate.py
- labman/gui/handlers/process_handlers/__init__.py
- labman/gui/handlers/process_handlers/gdna_extraction_process.py
- labman/gui/handlers/process_handlers/test/test_gdna_extraction_process.py
- labman/gui/templates/extraction.html
- labman/gui/templates/sitebase.html
- labman/gui/test/test_plate.py
- labman/gui/testing.py
- labman/gui/webserver.py
> Adds Extraction

- labman/db/support_files/db_patch.sql
- labman/db/support_files/labman.dbs
- labman/db/support_files/labman.html
- labman/gui/static/js/plate.js
- labman/gui/static/js/plateViewer.js
- labman/gui/static/js/reagentModal.js
- labman/gui/templates/extraction.html
- labman/gui/templates/library_prep_16S.html
- labman/gui/templates/plate.html
- labman/gui/templates/sitebase.html
Solving various issues:
Fixes #17 
Fixes #18 
Fixes #22
Fixes #23
Fixes #28
Fixes #30
Fixes #36
Fixes #47
> Solving misc issues

- labman/db/plate.py
- labman/db/tests/test_plate.py
This function is needed by other developers to accomplish their tasks
> Adding quantification process to plate

- labman/gui/static/js/labman.js
- labman/gui/templates/plate.html
There are multiple places where we will need to input the name of a plate, this function allows to check if the plate name exists or not.
> Abstracting plate name check for code reusability

- labman/db/process.py
This improves plate compression logic and allows single plates to be compressed to 384-well
> updated plate compression logic

- labman/gui/handlers/process_handlers/__init__.py
- labman/gui/handlers/process_handlers/gdna_compression_process.py
- labman/gui/handlers/process_handlers/test/test_gdna_compression_process.py
- labman/gui/templates/compression.html
- labman/gui/templates/sitebase.html
Still needs correct gDNA added to the database before unit-test can pass.
> added gDNA plate compression function

- labman/db/plate.py
- labman/db/support_files/db_patch_manual.sql
- labman/db/tests/test_plate.py
- labman/gui/handlers/plate.py
- labman/gui/handlers/process_handlers/sample_plating_process.py
- labman/gui/handlers/process_handlers/test/test_sample_plating_process.py
- labman/gui/static/css/labman.css
- labman/gui/static/js/plateViewer.js
- labman/gui/templates/plate.html
- labman/gui/test/test_plate.py
This adds the functionality to the plate object to search for plates based on different parameters and the ability to find the duplicated samples in a plate. Note, this is just backend - no interface yet.
> Duplicates and search

- labman/db/process.py
- labman/db/support_files/more_test_data.py
@tanaes requested an easy way of adding more data to the test system.
This adds a script that you can run as many time as you want and it will be adding more data to the DB
> Adding more data to test in a script

- labman/db/process.py
- labman/db/support_files/db_patch.sql
- labman/db/support_files/labman.dbs
- labman/db/support_files/labman.html
- labman/db/support_files/populate_test_db.sql
- labman/db/tests/test_process.py
We can sequence a pool per lane - fix the sequencing process to store that information.
> Fix sequencing process

- labman/gui/static/css/labman.css
- labman/gui/templates/plate.html
- html change consist in adding a table with the currently 3 controls: (col1) control name (col2) control descrition
- javascript change consist in addind a non-jquery/pure-javascript on click function to show the popup
- labman.ccs was amended for the popup => please change class names at your discretion as I don't know whether other popups will be used.
> popup showing plate controls description

- labman/gui/handlers/study.py
- labman/gui/templates/sitebase.html
- labman/gui/templates/study_list.html
- labman/gui/webserver.py
Created `study_list.html` and had it interacting with the front page. Modified from `pool_list.html`. Things are working except for that the `View study` button redirects to nowhere since the study information page is not present yet.
> created study list page

- README.md
- labman/gui/handlers/plate.py
- labman/gui/templates/plate_search.html
- labman/gui/templates/sitebase.html
- labman/gui/test/test_plate.py
- labman/gui/webserver.py
I believe this completes the work for issue #76, with the single exception that I can't run the unit tests on my system so I can't verify that my gui/test/test_plate.test_post_plate_search_handler test is passing (although I have of course done manual testing :) This test code is currently commented out and needs to be commented in and verified by someone who can run the unit tests ...
> Plate search

- labman/gui/handlers/process_handlers/normalization_process.py
- labman/gui/handlers/process_handlers/test/test_normalization.py
- labman/gui/templates/normalization.html
- normalization_process.py: use get_arguments to return a list
- normalization.html:
* added "+Add plate" button and its modal (copy from extraction.html) 
* toggleAddPlate function to disable "+Add plate" button after modal choice (hence, unnecessary addBtnPlate disabling property has been removed)
* added remove plate button and re- toggleAddPlate to re-enable "+Add plate" button
Note1: the normalization page cannot be accessed yet from the navigation menu
Note2: clicking Normalize / normalize_send() throw an error (under development I assume)
> Modified handler: no param required + plate search interface

- labman/gui/templates/library_prep_shotgun.html
Essentially same changes as for normalization.html
> Enable plate addition and removal + empty volume input set to zero

- labman/db/plate.py
- labman/db/tests/test_plate.py
- labman/gui/handlers/plate.py
- labman/gui/templates/plate_list.html
- labman/gui/test/test_plate.py
- labman/gui/webserver.py
the actual redirects from the plate view icon redirect correctly but don't show the information. They will be showing the information once https://github.com/jdereus/labman/issues/101 is fixed.
> Fixes #100

- labman/gui/handlers/process_handlers/library_prep_shotgun_process.py
- labman/gui/handlers/process_handlers/normalization_process.py
- labman/gui/handlers/process_handlers/pooling_process.py
- labman/gui/handlers/process_handlers/sequencing_process.py
> Sequence list

- labman/db/process.py
- labman/db/tests/test_process.py
> added parsable contact email field header to sample sheet generation

- labman/gui/handlers/study.py
- labman/gui/templates/study.html
- labman/gui/templates/study_list.html
- labman/gui/webserver.py
Hello @josenavas I need your help in resolving this. I was trying to create a "study.html" page to display study information, but I couldn't get the "view study" button to navigate to this page, after many unsuccessful trials. Perhaps it was some small issue I missed. Here I am posting a blank page with (what I think) necessary linkings. Can you please take a look and let me know what is missing? Thanks!
> Study summary page

- labman/db/equipment.py
- labman/db/tests/test_equipment.py
- labman/gui/handlers/process_handlers/__init__.py
- labman/gui/handlers/process_handlers/equipment_creation_process.py
- labman/gui/templates/equipments.html
- labman/gui/templates/sitebase.html
Addressed issue #117 . Tested and working.
> added create equipments page

- labman/db/process.py
- labman/db/support_files/db_patch.sql
- labman/db/support_files/labman.dbs
- labman/db/support_files/labman.html
- labman/db/support_files/populate_test_db.sql
- labman/db/tests/test_process.py
- labman/gui/handlers/process_handlers/gdna_extraction_process.py
- labman/gui/handlers/process_handlers/library_prep_16s_process.py
- labman/gui/handlers/process_handlers/test/test_gdna_extraction_process.py
- labman/gui/handlers/process_handlers/test/test_library_prep_16s_process.py
- labman/gui/templates/extraction.html
- labman/gui/templates/library_prep_16S.html
@AmandaBirmingham brought to my attention that the gDNA extraction process and amplicon library processes where used incorrectly. I introduced a set of tables in January 17 that broke the actual assumption behind those processes, so here I fix the DB schema, fix the objects and the interface to behave as expected.
In short: each process instance applies to a single plate (rather than a set of plates as I had it before).
@AmandaBirmingham this is the DB structure define here, does it correctly match your expectations?
> Fixing DB schema error

- labman/db/study.py
- labman/db/tests/test_study.py
- labman/gui/handlers/study.py
- labman/gui/templates/study.html
- labman/gui/test/test_study.py
Fixes: https://github.com/jdereus/labman/issues/50
Example view:
This includes the commits by @mortonjt and @qiyunzhu
> Study summary

- labman/gui/templates/pool_pooling.html
> Correct typo

- labman/gui/handlers/process_handlers/gdna_compression_process.py
- labman/gui/handlers/process_handlers/test/test_gdna_compression_process.py
- labman/gui/templates/compression.html
This fixes issue #146, including 1. listing wrong plate type, and 2. listing wrong robot type.
> gDNA plate compression fixes

- labman/db/study.py
- labman/db/tests/test_study.py
Case insensitive searching, fixes #116
> fixes #116

- labman/gui/templates/plate_list.html
> Add picogreen

- labman/gui/static/js/plate.js
> Activate a plate if none are added

- labman/db/exceptions.py
- labman/gui/templates/library_pooling.html
- labman/gui/templates/plate_search.html
- labman/gui/templates/sequencing.html
Fixes #89 
Fixes #134 
Fixes #147 
Fixes #160
> Misc fixes

- labman/gui/handlers/process_handlers/library_prep_16s_process.py
- labman/gui/handlers/process_handlers/library_prep_shotgun_process.py
- labman/gui/templates/library_prep_shotgun.html
fixes issue #164, from converting Plates.list_plates to accept a list and not a string
> Library primer plates fix

- labman/gui/static/css/labman.css
- labman/gui/static/js/plateViewer.js
- labman/gui/templates/plate.html
@josenavas, I ended up having to correct some of the indices. Turns out it is not very easy to hide a column from the data without deleting the information altogether. Please double check the changes I've made to "uncorrect" indices, I don't have a good way to validate that these are indeed accurate.
> Add a frozen column for the row names.

- labman/db/user.py
> fixed nameless user sample sheet download

- labman/gui/handlers/process_handlers/quantification_process.py
- labman/gui/templates/parse_quantification.html
> fixed name on quant page

- labman/gui/static/js/plateViewer.js
Fixes a +/-1 error. The problem seemed to be coming from the modifyWell method, this amends some a change introduced in #169. @josenavas, it would be very useful if you could do a review of the file/functionality. 👍 
Fixes #178
> BUG: Fix duplication of entries in spreadsheet

- labman/gui/static/js/plateViewer.js
Fixes updateDuplicates and updateUnknown to update all rows instead of
just the recently edited ones, this is important as a change in one cell
can affect other existing cells.
Fixes #189
> BUG: Fix cell rendering bug

- labman/gui/static/js/labman.js
- labman/gui/templates/library_pooling.html
- labman/gui/templates/sitebase.html
The new functionality comes from talking to @tanaes. When visualizing concentrations in a plate (as represented by a heatmap), it is useful to change the range of the colorscale, in order to do this, we've added a slider to manipulate this value, and set some appropriate defaults depending on the plate types. This will also be useful as we reuse this component for other steps in the processing pipeline.
Demo of the new functionality:
I've also cleaned up some of the JS code to avoid multiple traversals of the main arrays.
> Interactivity improvements

- labman/gui/static/js/labman.js
> BUG:Clear existing plots before creating a new one

- labman/gui/static/js/plateViewer.js
This should only happen when:
A study is selected, the sample name is not one of the known blank
names, and the sample name does not already include the study
identifier.
Fixes #209
This animated gif shows how this works (note that the first study I select has study id 2, and then the second study I select has study id 1):
> ENH: Prepend study identifiers to samples

- labman/gui/handlers/process_handlers/__init__.py
- labman/gui/handlers/process_handlers/quantification_process.py
- labman/gui/handlers/process_handlers/test/test_quantification_process.py
- labman/gui/static/js/labman.js
- labman/gui/templates/library_pooling.html
- labman/gui/templates/plate_list.html
- labman/gui/templates/quantification.html
- labman/gui/templates/view_quantifications.html
Fix for issue #195. This adds an interface for viewing the quantifications of a plate. 
It displays all quantifications associated with a plate.
> Interface to view previous quantifications

- labman/db/process.py
- labman/db/support_files/db_patch.sql
- labman/db/support_files/db_patch_manual.sql
- labman/db/support_files/populate_test_db.sql
- labman/db/tests/test_composition.py
- labman/db/tests/test_equipment.py
- labman/db/tests/test_process.py
- labman/gui/handlers/composition_handlers/test/test_reagent_composition.py
- labman/gui/handlers/process_handlers/gdna_extraction_process.py
- labman/gui/handlers/process_handlers/test/test_gdna_extraction_process.py
- labman/gui/static/js/labman.js
- labman/gui/templates/extraction.html
Tackling issue #168 
- Add input box "notes" (done)
- Add check box "externally extracted" (partial)
> Adding notes and external extraction (Issue 168)

- labman/db/process.py
> Use centralized date format

- labman/db/process.py
Add constants holding 'Amplicon' and 'Metagenomics' strings, modify throughout process.py code to set/compare to constants rather than to hard-coded strings
> Add constants holding 'Amplicon' and 'Metagenomics' strings in process.py

- .travis.yml
- labman/db/composition.py
- labman/db/study.py
- labman/db/tests/test_composition.py
- labman/db/tests/test_study.py
- labman/gui/handlers/plate.py
- labman/gui/handlers/process_handlers/sample_plating_process.py
- labman/gui/handlers/process_handlers/test/test_sample_plating_process.py
- labman/gui/static/js/plateViewer.js
- labman/gui/test/test_plate.py
Note, this PR is currently incomplete and still needs a fair amount of work
(mainly surrounding the tests). I've opened this PR to run the full test suite.
> Use tube identifiers to plate samples

- .travis.yml
- labman/db/study.py
Hotfix for Labman to make it compatible with the schema changes to Qiita's Jan '19 release.
> jsonb hotfix

- .travis.yml
- labcontrol/gui/templates/library_prep_shotgun.html
Update label based on Process description.
> Update label for shotgun volume field

- labcontrol/gui/templates/plate_list.html
https://github.com/jdereus/LabControl/issues/488
> fixed compressing 4+ gDNA plates issue

- labcontrol/db/study.py
Resolves issue in plate-mapper where the pull-down menu doesn't populate correctly if the search term is correct, but in a different case (upper vs lower vs mixed, etc.).
> Case-insensitive pull-down menu in plate-mapper
