labman/gui/templates/compression.html
that solves issue #73 (gDNA compression should allow to compress 1 plate)
- refreshing page was keeping any text written in "Compressed plate name" textbox.
Fix => reset jQuery value to empty string in document ready statement.
- glyphicon misaligned in "Compressed plate name" textbox (in a third rows between label and input)
Fix => add a \<div\> layer.
=> plate-ext-id input: .val('') to reset upon refreshing + align glyphicons

labman/db/process.py, labman/db/tests/test_process.py, labman/gui/handlers/sequence.py, labman/gui/templates/sequence_run_list.html, labman/gui/templates/sitebase.html, labman/gui/test/test_sequence_run.py, labman/gui/webserver.py
Adds interface page for listing sequence runs. 
Rather than redirecting to webpage for sample sheet download, we've just exposed relevant variables in the table and provided download links in the table itself.
=> Sequence run list interface

labman/gui/static/js/plateViewer.js, labman/gui/static/vendor/css/slick.grid.css, labman/gui/static/vendor/js/slick.editors.js, labman/gui/static/vendor/js/slick.grid.js, labman/gui/static/vendor/js/slickgrid.plugins/slick.cellexternalcopymanager.js, labman/gui/static/vendor/js/slickgrid.plugins/slick.cellrangedecorator.js, labman/gui/static/vendor/js/slickgrid.plugins/slick.cellrangeselector.js, labman/gui/static/vendor/js/slickgrid.plugins/slick.cellselectionmodel.js, labman/gui/static/vendor/licenses/SLICKGRID_LICENSE, labman/gui/templates/plate.html
This PR adds the ability to copy/paste text from Excel (fixes #42) and within the spreadsheet, example:
There's a few things to note for reviewers:
- If text is pasted into the cells and the contents exceed the available space, the extra text will be ignored.
- Users can paste from Excel and undo/redo the copy/paste actions, but only the copy paste actions.
- In order to start selecting cells within the table users need to hit ESC, otherwise the selection will be ignored (I've made a note of this in the UI).
- The SlickGrid files have been updated to match the latest tip of www.github.com/6pac/SlickGrid
- I submitted two PRs to 6pac/SlickGrid, because there were two bugs in the source (I've noted this in the License file).
- I made one cosmetic update in plateViewer.js to have the text …
=> Add the ability to copy and paste

labman/gui/handlers/process_handlers/__init__.py, labman/gui/handlers/process_handlers/sequencing_process.py, labman/gui/handlers/process_handlers/test/test_sequencing_process.py, labman/gui/templates/sequence_run_list.html
Adds a handler that creates a zip file with all the preparation files
for a given sequencing identifier. Also adds a button in the template
so users can download the data from the sequencing list table.
One thing I couldn't get around was that when running the test suite, the response's code was always 599, regardless of the URI (even endpoints that already existed). I couldn't test much, only via the UI. It would be good if someone can shed some light as to what else I can do, or if I'm missing something (maybe because of my local installation).
Fixes #86
=> ENH: Download preparations for a sequencing run

labman/gui/static/css/labman.css, labman/gui/static/js/plateViewer.js, labman/gui/templates/plate.html
Once users enter selection mode, auto editing is turned off so that
users can navigate the grid with the arrow keys. Also added some extra
formatting for the help text of the grid.
=> ENH: Makes edit/selection modes more amenable

labman/gui/static/js/plateViewer.js
Seems to be working now, except blank cells are saved with a blank placeholder i.e. if you paste 4 cells with no content, the grid will turn these into "blank entries". It's rather strange, before merging I recommend that you try this out locally. 
Fixes #120
=> Add undo/redo functionality

labman/gui/static/js/plateViewer.js
By updating modified rows we keep all the DOM elements that are currently present, this is important as it guarantees that active editors are not lost. This ultimately gets rid of a problem where switching between cells would result in requiring some awkward clicking to be able to edit the data again.
Not sure if I should repeat the comment block in every instance of `updateRow`, up to the reviewer.
=> ENH: Update rows instead of re-rendering them

labman/gui/templates/pool_pooling.html
The PoolingProcess class expects these values to be floats, however the
`val` function in JavaScript always returns strings (regardless of the
input type).
Fixes #181
=> BUG: Values were sent as strings instead of floats

labman/db/plate.py, labman/db/tests/test_plate.py, labman/gui/handlers/plate.py, labman/gui/templates/plate_list.html, labman/gui/test/test_plate.py
This patch makes two additions to the Plate class, first it adds a
"discarded" setter, and second it extends the functionality in the
list_plates method to be able to retrieve (or not) plates that have been
marked as discarded.
The PATCH handler is now aware about the discarded property. The UI uses
this route to make changes from the plate list. I've done some error handling using the bootstrapAlert function to handle the case where a "deletion" fails, not sure if something else is preferable.
Fixes #150
=> ENH: Add discard plate functionality

.travis.yml, labman/db/tests/tester.py
I've renamed the "integration_tests.py" script to "tester.py" and I've modified it to have another command that allows to add multiple data to the DB. Since the script can take a while to run (depending on the number of plates per workflow to create), the script prints the current progress so the user has some feedback:
```sh
$ labman/db/tests/tester.py stress_tests --num_plates 20
Amplicon workflow
Sample plating process....................Ok
gDNA extraction process....................Ok
Amplicon library prep process....................Ok
Amplicon library quantification process....................Ok
Plate pooling process....................Ok
Plate pool quantification process...Ok
Sequencing pool process...Ok
Sequencing process...Ok
Shotgun workflow
Sample plating …
```
=> Adding script to easily add data to the DB

labman/gui/static/css/labman.css
Adds some CSS to change the styling of the rows in a DataTables element. I noticed it was a bit confusing to try and click the add button on the right while trying to match a name on the left. Went from:
To:
=> ENH: Style odd and even rows to improve readability

labman/gui/handlers/process_handlers/quantification_process.py, labman/gui/static/js/labman.js, labman/gui/templates/quantification.html
The quantification step ditches the grid view and now reuses the display
element for the pooling step:
This PR also parametrizes the colormap to fit the step, by recommendation of @tanaes Viridis is used for quantification.
Related to #195
=> ENH: Add a heatmap display for the quantification step

labman/gui/static/css/labman.css, labman/gui/static/js/plateViewer.js
A handful of usability improvements in the main grid:
- Make the width of the columns adjustable.
- Improve the default width by 25% (from 80 to 100 pixels).
- Make the text in the column headers fully visible.
Animated gif for reference:
Fixes #210
=> ENH: Improve grid space usage

labman/db/plate.py, labman/db/tests/test_plate.py, labman/gui/handlers/plate.py, labman/gui/handlers/process_handlers/__init__.py, labman/gui/handlers/process_handlers/normalization_process.py, labman/gui/handlers/process_handlers/pooling_process.py, labman/gui/handlers/process_handlers/test/test_normalization.py, labman/gui/handlers/process_handlers/test/test_pooling_process.py, labman/gui/templates/library_pooling.html, labman/gui/templates/normalization.html, labman/gui/templates/plate_search.html, labman/gui/test/test_plate.py
Fixes #214 by adding support for Plate objects having quantitation_processes property rather than (incorrect) single quantitation_process, and user selecting the appropriate quantitation process for each plate during normalization and pooling. Also corrects spelling of ComputeLibraryPoolValuesHandler (was ComputeLibraryPoolValueslHandler).
=> Fix for Issue 214

labman/db/process.py
This: 
1. temporary changes numpy behavior to 'ignore' divide-by-zero warnings in the `compute_pooling_values_minvol` method. This leaves calculated volumes as `inf`.
2. removes deprecated static method `_compute_amplicon_pool_values`
I think the default numpy divide behavior here is the desired behavior -- producing `inf` volume values for cases where the measured concentration is zero.
Currently, these values get replaced by the 'floor_vol' value when 'floor_conc' is > 0. Maybe we should also add a constraint that requires `floor_conc` to be > 0?
=> handle warnings for divide by zero in pooling, fixes issue #233

labman/gui/static/js/plate.js
The grid wasn't being removed from the container after the plate
configuration changed. Leading to a stack of grids being added in the
UI.
Looks like this:
Fixes #241
=> BUG: Cleanup grid container before updating

labman/db/composition.py, labman/db/process.py, labman/db/tests/test_composition.py, labman/db/tests/test_process.py, labman/gui/handlers/pool.py, labman/gui/templates/pool_list.html, labman/gui/test/test_pool.py
Pool list now looks like the below, with pool file download buttons for plate pools and none for sequencing pools:
=> Fixes issue 251: Extend pool list to offer re-download of pool files for plate pools

labman/gui/static/js/plateViewer.js
The assignment of the `this.blankNames` property was being done
asynchronously on a per-cell basis. This worked fine if the user inputed
a value by hand, as it gave enough time for the request to return.
However, when someone copy-pasted text into the grid, the request
wouldn't return in time and the `this.blankNames` property wouldn't be
correctly assigned leading to a ReferenceError.
This is now fixed by getting the contents of `this.blankNames` before
initializing the whole grid. This way every cell has access to the data
before instantiation.
Fixes #243
=> BUG: Fix broken copy-paste

labman/db/process.py, labman/db/tests/test_process.py, labman/gui/handlers/plate.py, labman/gui/handlers/process_handlers/__init__.py, labman/gui/handlers/process_handlers/sample_plating_process.py, labman/gui/handlers/process_handlers/test/test_sample_plating_process.py, labman/gui/static/js/plateViewer.js, labman/gui/templates/extraction.html, labman/gui/test/test_plate.py
The user can now add notes to a plate during the plating process. These notes are later viewable when selecting plates in the extract gDNA UI. 
Here's an example of the new functionality. First I add a study to the plate, then add a sample, then when the process has been created the notes box is added to the UI. The user can add any text and save it with the "save" button.
Afterwards in the extract gDNA UI when a plate is selected the notes are shown at the bottom. See this animated gif for an example:
=> Adds sample plating notes to the UI

labman/gui/handlers/plate.py, labman/gui/static/js/plate.js, labman/gui/static/js/plateViewer.js, labman/gui/templates/plate.html, labman/gui/templates/plate_list.html, labman/gui/test/test_plate.py
This PR was written by @AmandaBirmingham and me. Briefly:
- This PR addresses #272: The error was caused because the plate UI incorrectly allowed for the addition of multiple samples before the plate was created. The UI has now been modified to make the plate creation step a requirement before the grid is displayed.
- This also fixes a problem where listing plates without study identifiers would result in the page crashing or no plates being loaded.
- Fixes a problem with viewing an existing plate where 384 plates would now be fully displayed on screen.
- Fixes a problem where the notes would note be loaded when viewing an existing plate.
- This adds a placeholder for the *Notes* widget in the sample plating interface.
Animated GIF:
=> Sample plating improvements

.travis.yml, README.md, scripts/labman
With added text in readme and a travis change to test fix, per Antonio
=> fix #315 : Correct name of key file attribute of ConfigurationManager in start-up script

labman/db/process.py, labman/db/tests/test_process.py
Argh, apparently *some* of the plate-readers produce files that end with CRLF (rather than just LF or just CR, as we saw in previously provided examples).  The tests are longer than the actual fix :-/
EDIT: logged a bug for this.  fixes #337
=> Add handling for CRLF line endings to Pico Green quantification file handling

labman/db/process.py, labman/db/support_files/db_patch.sql, labman/db/support_files/labman.dbs, labman/db/support_files/labman.html, labman/db/support_files/populate_test_db.sql, labman/db/tests/test_plate.py, labman/db/tests/test_process.py, labman/db/tests/tester.py, labman/gui/handlers/process_handlers/gdna_extraction_process.py, labman/gui/handlers/process_handlers/library_prep_16s_process.py, labman/gui/handlers/process_handlers/pooling_process.py, labman/gui/templates/sequence_run_list.html
Migrated from PR 330, work by @antgonza  :
closes #329 change from timestamptz to timestamp for process dates
fixes #336 ensure Process.get_date_format() is used for date display
fixes #326 disable preparation sheet download for shotgun runs
=> Closes #329 change from timestamptz to timestamp for process dates

README.md, docs/index.rst, labman/db/tests/tester.py, labman/gui/handlers/process_handlers/sample_plating_process.py, labman/gui/static/js/plateViewer.js, labman/gui/templates/plate_list.html, scripts/labman
Closes #356 Reduce number of GET calls during sample plating
Closes #353 Prevent unhandled exception when trying to plate a sample without a study selected
Closes #359 Upgrade command-line command names to work with click library version 7
Closes #357 Prevent uninformed discarding of plates
Closes #358 Include database permission requirements in install directions
=> Fix breaking issues identified during initial real-data test

labman/db/support_files/db_patch_manual.sql, labman/db/support_files/populate_test_db.sql, labman/db/tests/test_composition.py, labman/db/tests/test_container.py, labman/db/tests/test_plate.py, labman/db/tests/test_process.py, labman/gui/handlers/process_handlers/library_prep_shotgun_process.py, labman/gui/handlers/process_handlers/sequencing_process.py, labman/gui/handlers/process_handlers/test/test_library_prep_shotgun_process.py, labman/gui/handlers/process_handlers/test/test_sample_plating_process.py, labman/gui/handlers/process_handlers/test/test_sequencing_process.py, labman/gui/templates/compression.html, labman/gui/test/test_plate.py, labman/gui/test/test_sequence_run.py
TL;DR: Fix for #369 Support "externally extracted" gDNA plates in production-like databases
During real-data testing against labman on qiita-rc, I discovered that the externally extracted gDNA plates functionality did not work because it depend on a number of dummy records in the database, and those records are added in the populate_test_db.sql script--which is not run when a production-like database is created.  This PR moves that functionality out of  populate_test_db.sql 
and into db_patch_manual.sql--and then updates what-feels-like-zillions of hard-coded process and composition ids in the tests that are affected by having those records created before the test records rather than after them.
=> Support externally extracted gDNA plates in production

labman/db/process.py, labman/db/tests/test_process.py
sample names and sample plate names must now contain only alphanumeric
characters, '_', and '-', when creating a new sample sheet. This commit
duplicates earlier commit to private fork.
=> Added name validation to sample sheet creation

labman/db/composition.py, labman/db/tests/test_composition.py
This PR tests the object type of all compositions and errors if more than one are in a pool. This should fix #267
=> Fixes #267

.travis.yml, labman/db/tests/tester.py
This should facilitate populating the resource with a realistic volume of plates. 
On my local system, I now have 250 sample plates with a mix of 96 and 384. There are high loads that are observed on some UI elements, but I have not done a rigorous evaluation yet. Anecdotal measurements via `top` suggest that, in general, delay is derived from load on the database backend.
=> Update stress testing script

labman/db/process.py
EpMotion input file will now be in Windows text format, with CRLF
('\r\n') terminating each line, as opposed to LF ('\n') found on MacOSX/*NIX
systems.
=> EpMotion input file modified to support Windows

README.md, scripts/labman
In README.md, change labman to labcontrol (some of these are necessary for install instructions to continue to work), add note about necessity of qiita webserver running on port 8383 (now necessary for unit tests).  Also update echoed statement run on labcontrol webserver start to say "LabControl" instead of "Labman".
Addresses #460 and continues to chip away at #394 .
=> Fix install instructions in README

labcontrol/gui/templates/sitebase.html
Accidentally pushed this branch to the original fork. However, since it's here:
Adding Help menu option, with link to https://github.com/jdereus/labman/blob/master/docs/index.rst
=> Fixes #284

labcontrol/gui/static/js/labman.js, labcontrol/gui/templates/plate.html
Before working through the rest of th to resolve #304, does this type modification work? It adds a human readable message about the status in addition to color and icon. For some pages, the strategy may need to differ.
=> WIP: Clarify icon meaning (#304)

labcontrol/gui/static/js/plateViewer.js
Update well comments area when a cell changes, fixes #355
=> Update well comments when a cell changes

labcontrol/gui/static/js/plateViewer.js
I did not observe any oddities using the described suggested javascript modifications to the character restrictions.
Before:
After:
=> Fixes #456

labcontrol/gui/static/js/addPlateModal.js
plate modal was not being populated after addPlateModal.js refactor :(  I had reversed the order of two parameters and failed to pass one that I changed from default to explicit.
=> Fixes bug reported by MacKenzie of empty add plate modal

labcontrol/gui/static/css/labcontrol.css, labcontrol/gui/templates/plate.html
Fixes #432 
*Current Behavior*
There is no legend detailing the meaning of cell colors on the plate mapper interface (seen below)
*Proposed Behavior*
This PR adds a legend detailing the meaning of the possible cell colors on the plate mapper interface (seen below)
=> Issue432 cell color legend

labcontrol/gui/static/css/labcontrol.css, labcontrol/gui/templates/plate.html
Text for invalid specimen ids implied id would not exist across all
studies, when it's only against the studies associated with the plate.
Added a new yellow candy-cane/barber-bar to represent a cell that was
populated using a multiselect paste and has more than one possible
specimen ID match across the attached studies. This is so the user can
be alerted, click on the cell, and select from the drop-down that should
appear.
Modified the colors to be more appealing. Looking for collective
feedback. Bold red is gone, and an invalid specimen ID is now the red
candy-cane color. Blue candy-cane color is the same as before,
representing a specimen ID that has already been plated on another
plate.
A new Yellow/Orange candy-cane stripe identifies values that match more
than one possible specimen …
=> Modified PlateViewer colors + Legend

labcontrol/gui/static/js/plate.js, labcontrol/gui/static/js/plateViewer.js, labcontrol/gui/templates/plate.html
Closes #354 and closes #567, and represents partial progress on #553. Details:
This PR implements the solution described by @wasade in #464. It's a pretty simple solution, thankfully.
Note that this checkbox defaults to "checked" (i.e. multiselect pasting is enabled, at the expense of the autocomplete popping up on pasting). _However_, if the page loads and the checkbox isn't checked (due to browser back/forward button shenanigans analogous to those causing #562), then my code respects that and holds off on registering the CECM plugin accordingly.
Something worth noting is that testing this on the 384-well plates is an ...interesting experience, because the autocomplete takes a few seconds to activate when pasting something in for a given cell. (But it does show up eventually.) Improving …
=> Add a checkbox that allows autocomplete-from-paste and multiselect functionality to coexist; resolve duplicate plate issue

.travis.yml, Makefile, labcontrol/gui/js_tests/addPlateModal_tests.js, labcontrol/gui/static/css/labcontrol.css, labcontrol/gui/static/js/addPlateModal.js, labcontrol/gui/static/js/labcontrol.js, labcontrol/gui/static/js/plate.js, labcontrol/gui/static/js/plateViewer.js, labcontrol/gui/static/js/reagentModal.js, labcontrol/gui/templates/plate.html, labcontrol/gui/templates/plate_list.html
We can swap out prettier / change configs / etc. really easily, if desired (all that is needed is updating the Makefile, which I added as part of this PR).
This PR *looks* hairy because it includes a lot of changes. However, the bulk of these are just automatic changes from running `make festyle` (and this is prefaced by doing a dry run with the `--debug-check` option, to check that stuff won't get broken by running `prettier --write`).
**For reviewers**, I'd suggest mainly just looking at the non-auto-formatter changes (which should be localized to the Travis YAML, the newly added Makefile, and plate.html + plate_list.html). This PR doesn't run prettier on the HTML yet (for reasons explained in the Makefile), so all of these changes aren't the result of prettier autoformatting …
=> Address two #562 bugs; integrate "prettier" autoformatter for JS and CSS code
